### ISSUE TITLE
Change style block ref

### ISSUE THREAD

**Issue by taozina0587** [UserZYF/zhang-dark#2]
Your work is fantastic! Your change to the search layout was very valuable. Thank you very much.

Friend, I would like to bold the letters inside "reference blocks". Would you help me?

![image](https://user-images.githubusercontent.com/90691302/162843758-1076eed0-dcf0-4cd2-9f37-c9d3b5b1685c.png)

I wish "Crime Comum" in reference block was in bold.

**Comment by UserZYF** [comment]
in theme.css
you can put this code in the file and save


.protyle-wysiwyg [data-node-id] span[data-type='block-ref'] {
    font-weight: bold;
}
